# Project
version=26.10-hotfix
group=org.craftamethyst
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Tritium
mod_author=QianMo_ProMax, ZCRAFT, KSmc_brigade
mod_id=tritium
license=MIT
credits=
description=An all-in-one optimization module dedicated to optimizing client-side rendering and server-side stability and fluency.
minecraft_version_range=[1.21.4, 1.21.5)
neo_form_version=1.21.4-20241203.161809

parchment_minecraft=1.21.4
parchment_version=2024.12.22

# Fabric
fabric_version=0.112.2+1.21.4
fabric_loader_version=0.16.9

# Forge
forge_version=54.0.10
forge_loader_version_range=[54,)


# NeoForge
neoforge_version=21.4.33-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#Mod Menu
mod_menu_version=13.0.3

# Cloth Config (shared version for all loaders)
cloth_config_version=17.+
fabric_cloth_config_version=17.0.144

#TCLib
tc=BwDf0EQD
tc_fabric=OZf7uYjw