# Project
version=26.10-hotfix
group=org.craftamethyst
java_version=21
# Common
minecraft_version=1.21
mod_name=Tritium
mod_author=QianMo_ProMax, ZCRAFT, KSmc_brigade
mod_id=tritium
license=MIT
credits=
description=An all-in-one optimization module dedicated to optimizing client-side rendering and server-side stability and fluency.
minecraft_version_range=[1.21, 1.22)
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.06.23
# Fabric
fabric_version=0.100.1+1.21
fabric_loader_version=0.15.11
# Forge
forge_version=51.0.17
forge_loader_version_range=[51,)
# NeoForge
neoforge_version=21.0.110-beta
neoforge_loader_version_range=[4,)
# Cloth Config (shared version for all loaders)
cloth_config_version=14.+
fabric_cloth_config_version=15.0.140
#TCLib
tc=BwDf0EQD
tc_fabric=OZf7uYjw
#Mod Menu
mod_menu_version=11.0.3
#LWJGL
lwjgl_version=3.3.3
# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 --enable-preview
org.gradle.daemon=false
