# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.10-hotfix
group=org.craftamethyst
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Tritium
mod_author=QianMo_ProMax,ZCRAFT,KSmc_brigade
mod_id=tritium
license=MIT
credits=
description=An all-in-one optimization module dedicated to optimizing client-side rendering and server-side stability and fluency.
minecraft_version_range=[1.19, 1.22)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.1.0
forge_loader_version_range=[47,)
# Cloth Config (fabric/forge for 1.20.1)
cloth_config_version=11.0.+
# Cloth Config (neoforge artifact used at compile-only in common to align with 1.21)
cloth_config_neoforge_version=19.+
#TCLib
tc=gdlhmMXr
tc_fabric=Fbv4reH5
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
